services:
  nginx:
    image: nginx:alpine
    container_name: lemp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
    networks:
      - lemp-network

  php-fpm:
    build: ./php
    container_name: lemp-php
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - lemp-network

  mysql:
    image: mysql:8.0
    container_name: lemp-mysql
    env_file: .env
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge

volumes:
  mysql_data:

